    eureka:
      instance:
        hostname: localhost
      client:
        registerWithEureka: false
        fetchRegistry: false
    server:
      port: 8761
      waitTimeInMsWhenSyncEmpty: 0
      serviceUrl:
        defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    
    
    spring:
      datasource:
        driverClassName: com.mysql.jdbc.Driver
        url: 
        username: 
        password: 
      jpa:
        hibernate.ddl-auto: update
        generate-ddl: true
        show-sql: true
      main:
       allow-bean-definition-overriding:
        true
      application:
        name: security-gateway
      profile:
        docker
      











 